[package]
name = "bevy_mod_replication"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_renet = "0.0.7"
bevy = { version = "0.10", default-features = false }
bincode = "1.3"
serde = "1.0"
tap = "1.0"
strum = { version = "0.24", features = ["derive"] }
derive_more = { version = "0.99", default-features = false, features = [
  "constructor",
] }

[dev-dependencies]
serde_test = "1.0"
